### ISSUE TITLE
Add Auth

### ISSUE THREAD

**Issue by jp-quintana** [jp-quintana/flaakko#33]
# Tasks
Setup authentication with auth and implement cart/auth logic.

## Firebase
 - [x] Add auth.
 - [x] Add firestore.
 
## User & Cart
- [x] Add Auth Context.
- [x] Update Cart Context so it works wit new auth logic.
- [x] Add custom hooks for auth and cart operations.

**Comment by jp-quintana** [comment]
Done
