### ISSUE TITLE
Create User Profile Page

### ISSUE THREAD

**Issue by jp-quintana** [jp-quintana/flaakko#35]
# Tasks
Create UI for User Profile Page.

## Base User Profile
 - [x] Add base UI with orders, personal data and addresses section.

### Edit Profile Modal
- [x] Add modal to edit personal user data.

### Order Modal
- [x] Add modal to view details of each order user makes.

## Addresses Page
- [x] Create base UI for Addresses Page.

### Add/Edit Address Modal
- [x] Add modal to add new addresses or edit existing ones.
