### ISSUE TITLE
Update Nav & Add Route Guards

### ISSUE THREAD

**Issue by jp-quintana** [jp-quintana/flaakko#37]
# Tasks
Update nav UI and incorporate auth logic. Add protected routes.

## Update Nav
 - [x] Modify login link (icon to plain text).
 - [x] Update Nav UI
 - [x] Update SideNavUI
 - [x] Create SideModal

## Route Protection
- [x] Add protected routes.
